robot_radius: 0.2  
map_type: costmap

static_layer:
  enabled:              true
  unknown_cost_value: -1
  lethal_cost_threshold: 100
  
obstacle_layer:
  enabled:              true
  max_obstacle_height:  2.0
  origin_z:             0.0
  z_resolution:         0.2
  z_voxels:             10
  unknown_threshold:    10
  mark_threshold:       0
  combination_method:   1
  track_unknown_space:  false    #true needed for disabling global path planning through unknown space
  obstacle_range: 4.0 #for marking 4.0
  raytrace_range: 4.0 #for clearing 4.0
  publish_voxel_map: false
  observation_sources:  scan 
  scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    min_obstacle_height: -0.1
    max_obstacle_height: 1.5
    obstacle_range: 4.0 # 4.0
    raytrace_range: 4.0 # 4.0
 
inflation_layer:
  enabled:              true
  cost_scaling_factor:  1  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.30 # max. distance from an obstacle at which costs are incurred for planning paths. 0.35


  
